name: Build
on:
  push:
    tags:
      - 'b*-*-*'
jobs:
  Build-Upload-Release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        vers: ['-w', '-l']

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          python ${{ github.workspace }}/build.py ${{ matrix.vers }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-download
          path: |
            ${{ github.workspace }}/**/ff*build*.zip
          if-no-files-found: error
          retention-days: 30
