name: Build
on: [push]
jobs:
  Build-Upload-Release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          python ${{ github.workspace }}/build.py -w

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-download
          path: |
            ${{ github.workspace }}/**/ff*build*.zip
          if-no-files-found: error
          retention-days: 30
