name: Build
on:
  push:
    tags:
      - 'b*-*-*'

env:
  repo: ${{ github.event.repository.name }}
  ref: ${{ github.ref_name }}

jobs:
  Build-Upload-Release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        vers: ['-w', '-l']

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          python ${{ github.workspace }}/build.py ${{ matrix.vers }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repo }}-${{ env.ref }}
          path: |
            ${{ github.workspace }}/**/ff*build*.zip
          if-no-files-found: error
          retention-days: 60
